#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Builds the bot detection list from matomo/device-detector (bots.yml).
#
# Result: one RE2-compatible regex per line -> bots/bot_regex.list.
# lib_bots.sh combines the lines during import into ONE case-insensitive
# pattern; this makes bot detection Matomo-comparable instead of heuristic.
#
# License note: the patterns come from matomo/device-detector (LGPL-3.0-or-
# later, https://github.com/matomo-org/device-detector). The list is therefore
# NOT shipped in the repo/image, but generated by the operator (like GeoIP).
#
# Usage:  ./tools/fetch_bot_list.sh [TARGET-FILE]
#   ENV: BOTS_YML_URL  source URL (default: device-detector master)
# ---------------------------------------------------------------------------
set -euo pipefail
cd "$(dirname "$0")/.."   # -> ingestion/
OUT="${1:-bots/bot_regex.list}"
URL="${BOTS_YML_URL:-https://raw.githubusercontent.com/matomo-org/device-detector/master/regexes/bots.yml}"
# DuckDB-Binary: $DUCKDB-Override, sonst lokal gepinnt (Host/Tests: ./bin/duckdb),
# sonst aus PATH (Container: /usr/local/bin/duckdb).
if [ -z "${DUCKDB:-}" ]; then
  if [ -x bin/duckdb ]; then DUCKDB="$(pwd)/bin/duckdb"; else DUCKDB=duckdb; fi
fi

TMP_YML=$(mktemp); TMP_RAW=$(mktemp)
trap 'rm -f "$TMP_YML" "$TMP_RAW"' EXIT
echo ">> Lade ${URL}"
curl -fsSL -o "$TMP_YML" "$URL"

# Extract regex lines (YAML lines '- regex: ...', both quote styles) and
# discard RE2-incompatible constructs (lookaround, atomic groups,
# possessive quantifiers, backreferences - RE2 doesn't know them).
python3 - "$TMP_YML" > "$TMP_RAW" <<'PY'
import re, sys
kept = dropped = 0
for line in open(sys.argv[1], encoding='utf-8'):
    m = re.match(r"^- regex:\s*(.*)$", line.strip())
    if not m:
        continue
    v = m.group(1).strip()
    if v.startswith("'") and v.endswith("'"):
        v = v[1:-1].replace("''", "'")
    elif v.startswith('"') and v.endswith('"'):
        v = v[1:-1].replace('\\"', '"')
    if not v:
        continue
    if re.search(r"\(\?<[=!]|\(\?=|\(\?!|\(\?>|[*+?][+]|\\[1-9]", v):
        dropped += 1
        continue
    kept += 1
    print(v)
print(f">> {kept} Muster uebernommen, {dropped} RE2-inkompatible verworfen", file=sys.stderr)
PY

# Validation: compile each pattern individually in DuckDB (RE2); sort out
# broken patterns instead of failing during the nightly import.
mkdir -p "$(dirname "$OUT")"
{
  echo "# Quelle: ${URL}"
  echo "# Erzeugt: $(date -u +%Y-%m-%dT%H:%M:%SZ) von tools/fetch_bot_list.sh"
  echo "# Lizenz der Muster: LGPL-3.0-or-later (matomo/device-detector)"
} > "$OUT"
ok=0; bad=0
while IFS= read -r pat; do
  if printf 'SELECT regexp_matches(%s, %s);\n' "'probe'" "'${pat//\'/\'\'}'" | "$DUCKDB" >/dev/null 2>&1; then
    printf '%s\n' "$pat" >> "$OUT"; ok=$((ok+1))
  else
    bad=$((bad+1))
  fi
done < "$TMP_RAW"
echo ">> Validiert: ${ok} Muster ok, ${bad} verworfen -> ${OUT}"

# Final test: compile the combined pattern once in full (as during import).
"$DUCKDB" -noheader -list <<SQL >/dev/null
SELECT regexp_matches('Mozilla/5.0 (compatible; Googlebot/2.1)', '(?i)(' || string_agg(line, ')|(') || ')')
FROM read_csv('${OUT//\'/\'\'}', columns={'line':'VARCHAR'}, delim='\t', header=false, quote='', escape='', ignore_errors=true)
WHERE trim(line) <> '' AND line NOT LIKE '#%';
SQL
echo ">> Kombiniertes Muster kompiliert. Aktivierung: Datei liegt am Standardpfad (bots/bot_regex.list) oder SM_BOT_RE_PATH setzen."
