# ---------------------------------------------------------------------------
# Shared bot list selection (sourced by load_cube.sh + fetch_loki_logs.sh).
# Expects: caller is in the ingestion/ directory (pwd).
#
# If a device-detector bot list is present (one regex per line, generated by
# tools/fetch_bot_list.sh), ONE combined RE2 pattern is built from it and
# provided as the SQL fragment BOT_SQL (sets the variable 'botregex').
# Without a list, BOT_SQL stays empty -> transform.sql uses the built-in heuristic.
#
# ENV: SM_BOT_RE_PATH  path to the list (default: bots/bot_regex.list)
# ---------------------------------------------------------------------------
SM_BOT_RE_PATH="${SM_BOT_RE_PATH:-$(pwd)/bots/bot_regex.list}"
BOT_SQL=""
if [ -f "$SM_BOT_RE_PATH" ]; then
  # Combination in SQL (string_agg) instead of in the shell heredoc: no quoting
  # issue with special characters in the patterns, and the list stays diffable as a file.
  BOT_SQL="SET VARIABLE botregex = (
    SELECT '(?i)(' || string_agg(line, ')|(') || ')'
    FROM read_csv('${SM_BOT_RE_PATH//\'/\'\'}',
         columns={'line':'VARCHAR'}, delim='\t', header=false, quote='', escape='', ignore_errors=true)
    WHERE trim(line) <> '' AND line NOT LIKE '#%');"
  echo ">> Bot-Filter: device-detector-Liste (${SM_BOT_RE_PATH})"
else
  echo ">> Bot-Filter: eingebaute Heuristik (keine Liste unter ${SM_BOT_RE_PATH}; siehe tools/fetch_bot_list.sh)"
fi
