log_format elastic_common_schema escape=json
    '{'
        '"@timestamp":"$time_iso8601",'
        '"client":{'
            '"ip":"$remote_addr",'
            '"port":"$remote_port"'
        '},'
        '"user":{'
            '"name":"$remote_user"'
        '},'
        '"server":{'
            '"ip":"$server_addr",'
            '"port":"$server_port"'
        '},'
        '"http":{'
            '"version":"$server_protocol",'
            '"request":{'
                '"duration":"$request_time",'
                '"bytes":"$request_length",'
                '"method":"$request_method",'
                '"body":{'
                    '"bytes":"$content_length"'
                '}'
            '},'
            '"response":{'
                '"status_code":"$status",'
                '"bytes":"$bytes_sent",'
                '"body":{'
                    '"bytes":"$body_bytes_sent"'
                '}'
            '},'
            '"tls":{'
                '"protocol":"$ssl_protocol",'
                '"cipher":"$ssl_cipher",'
                '"fingerprint":"$ssl_client_fingerprint"'
            '}'
        '},'
        '"user_agent":{'
            '"original":"$http_user_agent"'
        '},'
        '"HTTP":{'
            '"url_path": "$request_uri",'
            '"req":{'
                '"host":"$http_host",'
                '"cookie":"$http_cookie",'
                '"referer":"$http_referer",'
                '"content_type":"$http_content_type",'
                '"origin":"$http_origin",'
                '"x_forwarded_for":"$http_x_forwarded_for",'
                '"upgrade":"$http_upgrade",'
                '"sec_websocket_extensions":"$http_sec_websocket_extensions",'
                '"sec_fetch_dest":"$http_sec_fetch_dest",'
                '"sec_fetch_mode":"$http_sec_fetch_mode",'
                '"sec_fetch_site":"$http_sec_fetch_site",'
                '"sec_fetch_user":"$http_sec_fetch_user"'
            '},'
            '"res":{'
                '"set_cookie":"$sent_http_set_cookie",'
                '"content_type":"$sent_http_content_type",'
                '"upgrade":"$sent_http_upgrade",'
                '"sec_websocket_extensions":"$sent_http_sec_websocket_extensions"'
            '}'
        '},'
        '"NGINX":{'
            '"upstream":{'
                '"cache_status":"$upstream_cache_status",'
                '"status":"$upstream_status",'
                '"addr":"$upstream_addr",'
                '"response_time":"$upstream_response_time",'
                '"response_length":"$upstream_response_length"'
            '}'
        '},'
        '"trace":{'
           '"id":"$http_x_request_id"'
        '},'
        '"file":{'
            '"path":"$request_filename"'
        '},'
        '"xlog_origin":"proxycache",'
        '"xlog_properties":["web_server","nginx","containerized","internet_service"]'
    '}';
 
# access_log /dev/stdout elastic_common_schema;
# error_log /dev/stderr notice;
